baseurl = "http://jouvenal.me"
title = "jouvenal.me"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[params]
  author = "jouvenal.me"
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2021

  colorScheme = "dark"
  hidecolorschemetoggle = true
